# Generated by Django 5.2.6 on 2025-10-07 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_is_confirmed_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_details', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Cleaner', 'Cleaner'), ('Chef', 'Chef'), ('Other', 'Other')], max_length=50)),
                ('date_of_employment', models.DateField()),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('On leave', 'On leave'), ('Retired', 'Retired'), ('Terminated', 'Terminated')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
